%YAML:1.0
# the tum dataset directory, change it to yours! 
# dataset_dir: ./Data/Dataset/Kitti/dataset/sequences/00
dataset_dir: ./dataset/sequences/05

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

# 特征点的数量，用于地图构建、初始化、跟踪等。
num_features: 150
num_features_init: 50
num_features_tracking: 50
